--- 

- hosts: ubuntu
  become: true
  tasks:

  - name: update repository index
    tags: always
    apt:
      update_cache: yes

  - name: install apache2 and php package
    apt:
      name: 
        - apache2
        - libapache2-mod-php
